DELETE http://localhost:3001/api/persons/3

###

GET http://localhost:3001/api/persons/5901

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "James",
    "number": "123"
}

###

PUT http://localhost:3001/api/persons/617a03387819c7f9b82492ad
Content-Type: application/json

{
    "name": "Jas",
    "number": "123"
}